

export  enum Role {
        ADMIN='ADMIN',
        PRESTADOR_INDIVIDUAL='PRESTADOR_INDIVIDUAL',
        PRESTADOR_COLECTIVO='PRESTADOR_COLECTIVO',
        CLIENTE_COLECTIVO='CLIENTE_COLECTIVO',
        CLIENTE_INDIVIDUAL='CLIENTE_INDIVIDUAL'
}